### ISSUE TITLE
Designer comments/questions about PhET-iO instrumentation of navbar

### ISSUE THREAD

**Issue by arouinfar** [phetsims/joist#597]
@kathy-phet and I reviewed `general.navigationBar` in studio and had the following comments/questions. For brevity, `simName.general.navigationBar` has been removed from the front of the tandems, unless otherwise specified.

- [x] The children under `a11yButtonsHBox.keyboardHelpButton.keyboardHelpDialogCapsule.archetype` should follow the same pattern used in `phetButton.phetMenu.aboutDialogCapsule.archetype` in terms of what is read-only.
- [x] `a11yButtonsHBox.soundOnOffButton` should have a linked property to `general.soundManager.enabledProperty`.
- [x] Feature `titleTextNode.visibleProperty`
- [x] Feature `a11yButtonsHBox.keyboardHelpButton.visibleProperty`
- [x] Feature `a11yButtonsHBox.soundOnOffButton.visibleProperty`
 

* `a11yButtonsHBox` is not the most client-friendly name. Could it be something like `accessibilityButtons` instead? 

Assigning to @zepumph, but feel free to reassign to another dev if appropriate.

**Comment by zepumph** [comment]
Thanks! I'll get this done before GFL publication.

**Comment by zepumph** [comment]
- [ ] Oh I just saw that RichText links at the bottom of the AboutDialog are not read-only. I'm going to change that as part of this issue too.

**Comment by zepumph** [comment]
>a11yButtonsHBox is not the most client-friendly name. Could it be something like accessibilityButtons instead?

What do you think about getting rid of that middle container? 
`gravityForceLab.general.navigationBar.keyboardHelpButton`
`gravityForceLab.general.navigationBar.soundOnOffButton`

**Comment by zepumph** [comment]
>What do you think about getting rid of that middle container?

I talked with @arouinfar and that seemed best.

I implemented everything above. Each checkbox (ish) got its own commit, and then there was one `grunt update` at the end.

Over to you for review.

**Comment by arouinfar** [comment]
@zepumph looks good except `titleTextNode.visibleProperty` doesn't appear to be featured.

**Comment by zepumph** [comment]
Oops! I featured the Node and not its `visibleProperty`.  Fixed above. Closing

**Comment by arouinfar** [comment]
@kathy-phet and I found a few more things in the navbar, so it seems appropriate to re-open this issue.

- [ ] Can you please "feature" the titleTextNode.textProperty in the code (since its common).  energyFormsAndChanges.general.navigationBar.titleTextNode.textProperty
- [ ] The name of a screen needs to be changed in three places: the large/small home screen buttons & the navbar. This is problematic (see #601), as the client would need to change a screen name in 3 places. For example: 
`homeScreen.view.introScreenSmallButton.text.textProperty`
`homeScreen.view.introScreenLargeButton.text.textProperty`
`general.navigationBar.introScreenButton.text.textProperty`
- [ ] Once the above is handled, we would like to feature the textProperty for each screen. To maintain center-aligned text, we would need to leverage the layout work in #608.

**Comment by chrisklus** [comment]
@arouinfar I featured `titleTextNode.textProperty` in the above commits. Marking on-hold until work in #601 is complete.

**Comment by chrisklus** [comment]
Remaining items for this issue:

- [ ] Updated by CK: The name of a screen needs to be changed in two places: its home screen button & the navbar, for example:
`homeScreen.view.buttonGroup.introScreenButton.text.textProperty`
`general.view.navigationBar.introScreenButton.text.textProperty`

  CK: @samreid @zepumph recommendations for how to condense this? Some ideas: 
  * Make `navigationBar.introScreenButton.text.textProperty` read only and follow the home screen button's textProperty.
  * factor out a screenNameProperty and have both text's follow it. Not sure if there's a good place in the tandem structure for this, though.

- [ ] Once the above is handled, we would like to feature the textProperty for each screen. To maintain center-aligned text, we would need to leverage the layout work in #608.

**Comment by zepumph** [comment]
>factor out a screenNameProperty and have both text's follow it. Not sure if there's a good place in the tandem structure for this, though.

This is what I would prefer. I think that Screen.js should have a `nameProperty`. It is a bit weird because it won't be under `model` or `view`, but I, at this moment, may still be ok with that. 

Then that nameProperty can be passed around in joist instead of just `{string} name` like it is now (passed as an option to Screen.js)

What do you think about that?

**Comment by samreid** [comment]
That sounds reasonable to me, and matches patterns we have liked previously.

**Comment by chrisklus** [comment]
>What do you think about that?

Sounds good, I'll try it out!

**Comment by chrisklus** [comment]
Implemented above - @zepumph could you please review? Relevant commits are https://github.com/phetsims/studio/commit/4a4ffdc8804291a13f3f6b9dd0ae64a1c4d1a5c1 and https://github.com/phetsims/joist/commit/d29cd9522dd5d8f793e0f3099072932f6b785ed8. Also please note the TODO I added related to accessibility.

Since the button labels on the home screen and nav bar now listen to the value of screen.nameProperty, I made their text.textProperties `phetioReadOnly: true`. And I found one preexisting problem with layout, see #620.

**Comment by zepumph** [comment]
@chrisklus I was surprised to see that each screen's `nameProperty` doesn't have any phetioDocumentation. Do you think we should add it? I don't think it needs to be specific to the screen/sim, just a common string for all of them should be good.

**Comment by arouinfar** [comment]
@chrisklus can you also make each screen's `nameProperty` phetioFeatured?

**Comment by chrisklus** [comment]
>@chrisklus I was surprised to see that each screen's `nameProperty` doesn't have any phetioDocumentation. Do you think we should add it? I don't think it needs to be specific to the screen/sim, just a common string for all of them should be good.

Right, thanks for noticing this. I'm realizing it would have been better to run my proposed docs past you and @arouinfar before committing them, oops.

>@chrisklus can you also make each screen's `nameProperty` phetioFeatured?

Yes, done above - sorry I forgot this on my first pass.

Back to @zepumph to continue review, if you weren't finished before. Moved down/edited from above since my last https://github.com/phetsims/joist/issues/597#issuecomment-606191206 is buried:

Relevant commits to review are https://github.com/phetsims/studio/commit/4a4ffdc8804291a13f3f6b9dd0ae64a1c4d1a5c1, https://github.com/phetsims/joist/commit/d29cd9522dd5d8f793e0f3099072932f6b785ed8, and https://github.com/phetsims/joist/commit/811ad4d28b9eb3ccd2d284b539f21ba6d7fa9ab1. 

Also please note the TODO I added related to accessibility. Would you like a separate issue for this, and/or for me to take any action?

**Comment by chrisklus** [comment]
@zepumph pointed out another bug that came from this issue. Multi-screen sims that get reduced to a single screen by the `screens` QP have a title in the nav bar in the form of `Sim Name - Screen Name`. He noticed that `- Screen Name` is missing. I committed a fix above.

I missed a couple of cases when making this refactor because I was searching for usages incorrectly - it was impossible to look over all 1000+ cases of `.name` across the project, so I instead just looked for `screen.name` (and shortly after, `this.name` in Screen.js 🤦‍♂). But the better move was to look over every case of `.name` in `joist`, since that number is much more manageable. Since fixing this case, I've done that and feel good about all remaining usages of `.name` in `joist` not being in reference to a screen's name. Sorry for the trouble!

**Comment by zepumph** [comment]
I commented over in https://github.com/phetsims/joist/issues/627#issuecomment-614911233,

but we may be able to simplify the phetioType for the Screen name Property. I put it over there since it is in active development around the same code.


>Also please note the TODO I added related to accessibility. Would you like a separate issue for this, and/or for me to take any action?

I didn't see a TODO in Screen.js or NavigationBar.js, which one were you talking about?

>I missed a couple of cases when making this refactor because I was searching for usages incorrectly - it was impossible to look over all 1000+ cases of .name across the project, so I instead just looked for screen.name (and shortly after, this.name in Screen.js 🤦‍♂). But the better move was to look over every case of .name in joist, since that number is much more manageable. Since fixing this case, I've done that and feel good about all remaining usages of .name in joist not being in reference to a screen's name. Sorry for the trouble!

Sounds great!

Everything else here is looking really good. Thanks for implementing.

**Comment by chrisklus** [comment]
Thanks @zepumph. TODO is currently in line 95 of HomeScreenView.js. Basically, I'm wondering if descriptions should support the new Property nature of screen.name (and very soon, sim.name), or if leaving static support is sufficient (by just passing in the initial value of the Properties).

**Comment by zepumph** [comment]
Ahh I see thanks!. It would probably be the most robust to link the `innerContent` to the value of the screenProperty, like `screenNameProperty.link( name=> {homeScreenButton.innerContent = name });`

That said, it wouldn't change the behavior currently since there is nothing changing the home screen name. That and home screen's nameProperty is no longer instrumented. Does that sound good?

**Comment by chrisklus** [comment]
>It would probably be the most robust to link the `innerContent` to the value of the screenProperty, like `screenNameProperty.link( name=> {homeScreenButton.innerContent = name });`

Cool, thanks. I tested and committed that above.

>That said, it wouldn't change the behavior currently since there is nothing changing the home screen name. That and home screen's nameProperty is no longer instrumented.

HomeScreenButton is the sim-specific screen buttons on the home screen that have instrumented screen names, so your solution above sounds great. Ready to close here?

**Comment by zepumph** [comment]
Looks great thanks!

@jessegreenberg, please look at https://github.com/phetsims/joist/commit/aafe1aa56a88c11158e383bc7ed7bea540710caf.

As a convention, do you think that the initial `innerContent` should be kept in options, even though the link call really handles the description? I am inclined slightly towards removing it from options. On one side it is a bit clearer to see that the Node has its innerContent set when you are looking at the options, on the other side, it is a bit of a misnomer because it may imply that it is static until you see the link below. Do you have any thoughts about if we should keep the `innerContent` option?

**Comment by zepumph** [comment]
Ping on @jessegreenberg, as this has been up for review for a year.

**Comment by zepumph** [comment]
Hey @jessegreenberg, I'm going through old phet-io design issues right now, and came across this one again. Could you please take a look at just https://github.com/phetsims/joist/issues/597#issuecomment-624860692 to review.

**Comment by zepumph** [comment]
Just a ping on this guy

**Comment by jessegreenberg** [comment]
Oof, Im sorry about this.

I reviewed https://github.com/phetsims/joist/commit/aafe1aa56a88c11158e383bc7ed7bea540710caf, it looks great.

> o you think that the initial innerContent should be kept in options, even though the link call really handles the description? I am inclined slightly towards removing it from options.

I was going to recommend removing it from `options` and see that it has since been removed. Closing.
